src/main/java/com/cwallet/CHAMPWallet/models/ExpenseEntity.java

addSomething

---

src/main/java/com/cwallet/CHAMPWallet/ChampWalletApplication.java
src/main/java/com/cwallet/CHAMPWallet/utils/EmailService.java
src/main/java/com/cwallet/CHAMPWallet/utils/EmailServiceImpl.java
src/main/resources/application.properties

added java mail

---

src/main/java/com/cwallet/CHAMPWallet/ChampWalletApplication.java
src/main/java/com/cwallet/CHAMPWallet/bean/account/EmailForm.java
src/main/java/com/cwallet/CHAMPWallet/bean/account/PasswordResetForm.java
src/main/java/com/cwallet/CHAMPWallet/controller/account/UserController.java
src/main/java/com/cwallet/CHAMPWallet/exception/account/AccountAlreadyActivatedException.java
src/main/java/com/cwallet/CHAMPWallet/exception/account/NoSuchAccountException.java
src/main/java/com/cwallet/CHAMPWallet/exception/account/VerificationAlreadyUsedException.java
src/main/java/com/cwallet/CHAMPWallet/models/account/UserEntity.java
src/main/java/com/cwallet/CHAMPWallet/repository/account/VerificationRepository.java
src/main/java/com/cwallet/CHAMPWallet/service/account/UserService.java
src/main/java/com/cwallet/CHAMPWallet/service/account/VerificationService.java
src/main/java/com/cwallet/CHAMPWallet/service/impl/account/UserServiceImpl.java
src/main/java/com/cwallet/CHAMPWallet/service/impl/account/VerificationImpl.java
src/main/java/com/cwallet/CHAMPWallet/utils/EmailService.java
src/main/java/com/cwallet/CHAMPWallet/utils/EmailServiceImpl.java
src/main/resources/application.properties
src/main/resources/templates/activation.html
src/main/resources/templates/password-reset.html
src/main/resources/templates/request-password-reset.html
src/main/resources/templates/request-verification.html
src/main/resources/templates/users-login.html
src/main/resources/templates/users-registration.html

- implemented registration functionality with password integrity validation.
- implemented verification request and account activation
- implemented login/logout functionality
- implemented password reset, also with password integrity validation

TRAC-1, TRAC-2, TRAC-3

---

src/main/java/com/cwallet/CHAMPWallet/bean/budget/BudgetForm.java
src/main/java/com/cwallet/CHAMPWallet/controller/budget/BudgetController.java
src/main/java/com/cwallet/CHAMPWallet/dto/budget/BudgetDTO.java
src/main/java/com/cwallet/CHAMPWallet/repository/budget/BudgetRepository.java
src/main/java/com/cwallet/CHAMPWallet/service/budget/BudgetService.java
src/main/java/com/cwallet/CHAMPWallet/service/impl/budget/BudgetServiceImpl.java
src/main/resources/templates/budget/budget-creation.html
src/main/resources/templates/budget/budget-list.html
src/main/resources/templates/home.html
src/main/resources/templates/users-login.html
src/main/resources/templates/users-registration.html

completed list view of budgets

TRAC37 - Budget List

---

src/main/java/com/cwallet/CHAMPWallet/controller/budget/BudgetController.java
src/main/java/com/cwallet/CHAMPWallet/exception/budget/BudgetExpiredException.java
src/main/java/com/cwallet/CHAMPWallet/exception/budget/NoSuchBudgetOrNotAuthorized.java
src/main/java/com/cwallet/CHAMPWallet/repository/budget/BudgetRepository.java
src/main/java/com/cwallet/CHAMPWallet/repository/expense/ExpenseRepository.java
src/main/java/com/cwallet/CHAMPWallet/service/budget/BudgetService.java
src/main/java/com/cwallet/CHAMPWallet/service/impl/budget/BudgetServiceImpl.java
src/main/java/com/cwallet/CHAMPWallet/utils/impl/ExpirableAndOwnedServiceImpl.java
src/main/resources/templates/budget/budget-detail.html

TRAC-38  Budget Details

---

src/main/java/com/cwallet/CHAMPWallet/controller/expenseType/ExpenseTypeController.java
src/main/java/com/cwallet/CHAMPWallet/dto/expenseType/ExpenseTypeDto.java
src/main/java/com/cwallet/CHAMPWallet/exception/expenseType/ExpenseTypeExpiredException.java
src/main/java/com/cwallet/CHAMPWallet/exception/expenseType/NoSuchExpenseTypeOrNotAuthorized.java
src/main/java/com/cwallet/CHAMPWallet/mappers/expenseType/ExpenseTypeMapper.java
src/main/java/com/cwallet/CHAMPWallet/repository/expenseType/ExpenseTypeRepository.java
src/main/java/com/cwallet/CHAMPWallet/service/expenseType/ExpenseTypeService.java
src/main/java/com/cwallet/CHAMPWallet/service/expenseType/impl/ExpenseTypeServiceImpl.java
src/main/resources/templates/create-expense-type-form.html
src/main/resources/templates/expense-type-details.html

Finished the expense type list and details with a verification if expired or not

TRAC-63(Expense Type Details)

---

src/main/java/com/cwallet/CHAMPWallet/bean/budget/BudgetForm.java
src/main/java/com/cwallet/CHAMPWallet/controller/budget/BudgetController.java
src/main/java/com/cwallet/CHAMPWallet/models/account/Wallet.java
src/main/java/com/cwallet/CHAMPWallet/models/budget/Budget.java
src/main/java/com/cwallet/CHAMPWallet/models/expense/Expense.java
src/main/java/com/cwallet/CHAMPWallet/models/expense/ExpenseType.java
src/main/java/com/cwallet/CHAMPWallet/models/income/Income.java
src/main/java/com/cwallet/CHAMPWallet/models/income/IncomeType.java
src/main/java/com/cwallet/CHAMPWallet/service/budget/BudgetService.java
src/main/java/com/cwallet/CHAMPWallet/service/impl/account/UserServiceImpl.java
src/main/java/com/cwallet/CHAMPWallet/service/impl/budget/BudgetServiceImpl.java
src/main/resources/templates/budget/budget-detail.html
src/main/resources/templates/budget/budget-list.html
src/main/resources/templates/budget/budget-update.html

- completed budget update
- added @ToString exclude to models to prevent infinite toString recursion

Trac39 - Budget Update

---

src/main/java/com/cwallet/CHAMPWallet/controller/budget/BudgetController.java
src/main/java/com/cwallet/CHAMPWallet/service/budget/BudgetService.java
src/main/java/com/cwallet/CHAMPWallet/service/impl/budget/BudgetServiceImpl.java
src/main/resources/templates/budget/budget-delete.html

TRAC40 - Budget Delete

---

src/main/java/com/cwallet/CHAMPWallet/bean/expenseType/ExpenseTypeForm.java
src/main/java/com/cwallet/CHAMPWallet/controller/expenseType/ExpenseTypeController.java
src/main/java/com/cwallet/CHAMPWallet/service/expenseType/ExpenseTypeService.java
src/main/java/com/cwallet/CHAMPWallet/service/expenseType/impl/ExpenseTypeServiceImpl.java
src/main/resources/templates/expense-type-details.html
src/main/resources/templates/expense-type-list.html
src/main/resources/templates/expense-type-update.html
src/main/resources/templates/update-expense-type-form.html

Added the feature:
- update expense type
- fix the error that if the updated expense type is clicked it will return to the expense type list page

TRAC-64(Expense Type Update)

---

src/main/java/com/cwallet/CHAMPWallet/bean/incomeType/IncomeTypeForm.java
src/main/java/com/cwallet/CHAMPWallet/controller/incomeType/IncomeTypeController.java
src/main/java/com/cwallet/CHAMPWallet/service/impl/incomeType/IncomeTypeServiceImpl.java
src/main/java/com/cwallet/CHAMPWallet/service/incomeType/IncomeTypeService.java
src/main/resources/templates/income-type-details.html
src/main/resources/templates/income-type-update.html

Added update functionality in Income type

---

src/main/java/com/cwallet/CHAMPWallet/controller/expenseType/ExpenseTypeController.java
src/main/java/com/cwallet/CHAMPWallet/dto/expenseType/ExpenseTypeDto.java
src/main/java/com/cwallet/CHAMPWallet/service/expenseType/ExpenseTypeService.java
src/main/java/com/cwallet/CHAMPWallet/service/expenseType/impl/ExpenseTypeServiceImpl.java
src/main/resources/templates/expense-type-delete.html
src/main/resources/templates/expense-type-details.html
src/main/resources/templates/expense-type-list.html

Finished the expense type delete ticket and remove the unused imports

TRAC-64(Expense Type Delete)

---

pom.xml
src/main/java/com/cwallet/CHAMPWallet/bean/income/IncomeForm.java
src/main/java/com/cwallet/CHAMPWallet/controller/account/UserController.java
src/main/java/com/cwallet/CHAMPWallet/controller/budget/BudgetController.java
src/main/java/com/cwallet/CHAMPWallet/controller/income/IncomeController.java
src/main/java/com/cwallet/CHAMPWallet/dto/income/IncomeDTO.java
src/main/java/com/cwallet/CHAMPWallet/repository/income/IncomeRepository.java
src/main/java/com/cwallet/CHAMPWallet/service/impl/income/IncomeServiceImpl.java
src/main/java/com/cwallet/CHAMPWallet/service/income/IncomeService.java
src/main/resources/application.properties
src/main/resources/templates/income/income-delete.html
src/main/resources/templates/income/income-detail.html
src/main/resources/templates/income/income-list.html
src/main/resources/templates/income/income-update.html
src/main/resources/templates/income/trydelete.html

TRAC 33-(income DElete)
DElete function 
TRAC 34-(income Update),
Update function

TRAC 34-(income Update),TRAC 33-(income DElete)

---

src/main/java/com/cwallet/champwallet/controller/budget/BudgetController.java
src/main/java/com/cwallet/champwallet/controller/budget/BudgetControllerRest.java
src/main/java/com/cwallet/champwallet/dto/budget/BudgetAllocationHistoryJson.java
src/main/java/com/cwallet/champwallet/dto/budget/BudgetJson.java
src/main/java/com/cwallet/champwallet/mappers/budget/BudgetAllocationHistoryMapper.java
src/main/java/com/cwallet/champwallet/mappers/budget/BudgetMapper.java
src/main/java/com/cwallet/champwallet/repository/budget/BudgetAllocationHistoryRepository.java
src/main/java/com/cwallet/champwallet/service/budget/BudgetAllocationHistoryService.java
src/main/java/com/cwallet/champwallet/service/impl/budget/BudgetAllocationHistoryImpl.java
src/main/resources/static/js/api.js
src/main/resources/static/js/custom.js
src/main/resources/static/js/modal.js
src/main/resources/static/js/ui.js
src/main/resources/templates/budget/budget-allocation-history.html
src/main/resources/templates/budget/budget-detail.html

completed budget allocation history

TRAC52 - Budget History

---

src/main/java/com/cwallet/champwallet/bean/BudgetTransferForm.java
src/main/java/com/cwallet/champwallet/controller/budget/BudgetController.java
src/main/java/com/cwallet/champwallet/dto/budget/BudgetTransferHistoryDTO.java
src/main/java/com/cwallet/champwallet/dto/budget/BudgetTransferHistoryJson.java
src/main/java/com/cwallet/champwallet/mappers/budget/BudgetTransferHistoryMapper.java
src/main/java/com/cwallet/champwallet/models/budget/Budget.java
src/main/java/com/cwallet/champwallet/models/budget/BudgetTransferHistory.java
src/main/java/com/cwallet/champwallet/repository/budget/BudgetTransferHistoryRepository.java
src/main/java/com/cwallet/champwallet/service/budget/BudgetService.java
src/main/java/com/cwallet/champwallet/service/budget/BudgetTransferHistoryService.java
src/main/java/com/cwallet/champwallet/service/impl/budget/BudgetServiceImpl.java
src/main/java/com/cwallet/champwallet/service/impl/budget/BudgetTransferHistoryServiceImpl.java
src/main/resources/templates/budget/budget-detail.html
src/main/resources/templates/budget/budget-transfer.html

completed fund transfer to another budget

TRAC43 - Credit to Another Budget

---

src/main/java/com/cwallet/champwallet/dto/expenseType/ExpenseTypeDto.java
src/main/java/com/cwallet/champwallet/service/expenseType/impl/ExpenseTypeServiceImpl.java
src/main/resources/templates/home.html
src/test/java/com/cwallet/champwallet/service/expenseType/impl/ExpenseTypeServiceImplTest.java

Added the testing for expense type

TRAC-64(Expense Type Test)

---

pom.xml
src/main/java/com/cwallet/champwallet/bean/Expense/ExpenseForm.java
src/main/java/com/cwallet/champwallet/controller/expense/expenseController.java
src/main/java/com/cwallet/champwallet/controller/income/IncomeController.java
src/main/java/com/cwallet/champwallet/dto/expense/ExpenseDTO.java
src/main/java/com/cwallet/champwallet/exception/expense/ExpenseExpiredException.java
src/main/java/com/cwallet/champwallet/exception/expense/NoSuchExpenseOrNotAuthorized.java
src/main/java/com/cwallet/champwallet/mappers/expense/ExpenseMapper.java
src/main/java/com/cwallet/champwallet/models/account/Wallet.java
src/main/java/com/cwallet/champwallet/repository/expense/ExpenseRepository.java
src/main/java/com/cwallet/champwallet/service/expense/ExpenseService.java
src/main/java/com/cwallet/champwallet/service/impl/expense/ExpenseServiceImpl.java
src/main/java/com/cwallet/champwallet/service/impl/income/IncomeServiceImpl.java
src/main/java/com/cwallet/champwallet/service/income/IncomeService.java
src/main/resources/application.properties
src/main/resources/templates/expense/add-expense.html
src/main/resources/templates/expense/expense-list.html
src/main/resources/templates/home.html
src/main/resources/templates/income/income-delete.html
src/main/resources/templates/income/income-update.html
src/test/java/com/cwallet/champwallet/bean/income/IncomeFormTest.java

Trac 29
-Display the total amount of expenses recorded, and display all the recorded expenses
Expense ADD
-add expenses, decreases the total balance from the choses budget base on the price allotted to the expense

TRAC 29(Expense List), TRAC (Expense ADD)

---

src/main/java/com/cwallet/champwallet/controller/budget/BudgetController.java
src/main/java/com/cwallet/champwallet/controller/budget/BudgetControllerRest.java
src/main/java/com/cwallet/champwallet/mappers/budget/BudgetTransferHistoryMapper.java
src/main/java/com/cwallet/champwallet/repository/budget/BudgetTransferHistoryRepository.java
src/main/java/com/cwallet/champwallet/service/budget/BudgetTransferHistoryService.java
src/main/java/com/cwallet/champwallet/service/impl/budget/BudgetTransferHistoryServiceImpl.java
src/main/resources/static/js/ui.js
src/main/resources/templates/budget/budget-allocation-history.html
src/main/resources/templates/budget/budget-detail.html
src/main/resources/templates/budget/budget-transfer-history.html

implemented the feature that allow users to view a budgets transfer history, and to also download the data into excel

TRAC-44, TRAC-45 - Incoming and Outgoing Transfer History

---

src/main/java/com/cwallet/champwallet/controller/budget/BudgetController.java
src/main/java/com/cwallet/champwallet/controller/budget/BudgetControllerRest.java
src/main/java/com/cwallet/champwallet/repository/budget/BudgetAllocationHistoryRepository.java
src/main/java/com/cwallet/champwallet/service/budget/BudgetAllocationHistoryService.java
src/main/java/com/cwallet/champwallet/service/impl/budget/BudgetAllocationHistoryImpl.java
src/main/resources/templates/budget/budget-allocation-history.html

added interval to allocation history, and download to excel

TRAC-66 - Budget History

---

src/main/java/com/cwallet/champwallet/controller/ExpenseControllerRest.java
src/main/java/com/cwallet/champwallet/controller/ExpenseTypeControllerRest.java
src/main/java/com/cwallet/champwallet/controller/expense/expenseController.java
src/main/java/com/cwallet/champwallet/dto/ExpenseJson.java
src/main/java/com/cwallet/champwallet/dto/ExpenseTypeJson.java
src/main/java/com/cwallet/champwallet/mappers/expense/ExpenseMapper.java
src/main/java/com/cwallet/champwallet/mappers/expenseType/ExpenseTypeMapper.java
src/main/java/com/cwallet/champwallet/repository/expense/ExpenseRepository.java
src/main/java/com/cwallet/champwallet/service/expense/ExpenseService.java
src/main/java/com/cwallet/champwallet/service/impl/expense/ExpenseServiceImpl.java
src/main/resources/templates/expense/expense-stats.html

1. completed the expense report functionality
2. users can now generate expense reports with data visualization and be able to export there expense data to an excel file

TRAC48 to TRAC51

---

src/main/java/com/cwallet/champwallet/service/impl/account/UserServiceImpl.java
src/main/java/com/cwallet/champwallet/utils/EmailService.java
src/main/java/com/cwallet/champwallet/utils/EmailServiceImpl.java
src/main/resources/application.properties

added mime message to our email service

MimeMessage to email service

---

src/main/java/com/cwallet/champwallet/models/account/Role.java
src/main/java/com/cwallet/champwallet/service/impl/account/UserServiceImpl.java
src/main/java/com/cwallet/champwallet/service/impl/account/VerificationImpl.java
src/main/resources/static/js/ui.js
src/main/resources/templates/budget/budget-allocation-history.html
src/main/resources/templates/budget/budget-detail.html
src/main/resources/templates/budget/budget-list.html
src/main/resources/templates/budget/budget-transfer-history.html
src/main/resources/templates/expense/expense-stats.html
src/main/resources/templates/layout.html
src/test/java/com/cwallet/champwallet/service/impl/BudgetServiceImpl.java
src/test/java/com/cwallet/champwallet/service/impl/UserServiceTest.java
src/test/java/com/cwallet/champwallet/service/impl/VerificationImplTest.java

finished unit test for user service and verification sevice

User Service Test

---

src/main/java/com/cwallet/champwallet/bean/PasswordForm.java
src/main/java/com/cwallet/champwallet/controller/budget/BudgetController.java
src/main/java/com/cwallet/champwallet/exception/BudgetAlreadyDisabledException.java
src/main/java/com/cwallet/champwallet/exception/BudgetAlreadyEnabledException.java
src/main/java/com/cwallet/champwallet/exception/BudgetDisabledException.java
src/main/java/com/cwallet/champwallet/exception/IncorrectPasswordException.java
src/main/java/com/cwallet/champwallet/service/budget/BudgetService.java
src/main/java/com/cwallet/champwallet/service/impl/budget/BudgetServiceImpl.java
src/main/resources/templates/budget/budget-detail.html
src/main/resources/templates/budget/budget-disable.html
src/main/resources/templates/budget/budget-enable.html

- added a feature that disables a budget
- a disabled budget couldn't be use in any transactions such as allocation or transfer
- a disabled budget will not appear as option to receive fund transfer and as a source of expense
- to disable a budget the user must provided their password
- to re-enable a budget the user must provide their password

TRAC54 - Disable/Enable budget
